### ISSUE TITLE
Legend not showing in selection: NVDI (Weekly)

### ISSUE THREAD

**Issue by piraces** [ismaro3/Cropper#1]
Apparently, while selecting OpenMaps and NVDI (Weekly), a legend image it's not showing correctly.
Here you can see the problem:
![captura](https://cloud.githubusercontent.com/assets/11027628/7159620/c218ea2e-e383-11e4-8166-0e9255fd78cb.PNG)

**Comment by ismaelrh** [comment]
¿Does it happen when you select only NVDI (Weekly)? Thanks

**Comment by piraces** [comment]
Only when I select this option, others appear to work well.

**Comment by ismaelrh** [comment]
Fixed.
