### ISSUE TITLE
General enhancements

### ISSUE THREAD

**Issue by RecuencoJones** [ismaro3/Cropper#4]
IMO the header of the tab which is active should be colored differently (for example white)

Referring the chat, I'm not really sure if it's working, but the caret should always be at the newest message [this may be useful](http://jsfiddle.net/jPVAf/50/).

Finally, for leaflet not to show the entire world repeated and prevent the user from scrolling the map infinitelly to the north, this should be useful [lines 93 to 100](https://github.com/unCoVered/SpaceApps2015/blob/master/src/main/webapp/js/services/geoService.js#L93)

**Comment by RecuencoJones** [comment]
And by the way, if you are going to prevent the user from dragging the map out of your bounds, make sure he can't zoom out to the minimum by placing a minimum zoom value [reference](https://github.com/unCoVered/SpaceApps2015/blob/master/src/main/webapp/js/services/geoService.js#L85)

**Comment by ismaelrh** [comment]
:(

**Comment by RecuencoJones** [comment]
Next time I will try to close it with a pull request ;)
