### ISSUE TITLE
Feature "Stats" don't shows anything.

### ISSUE THREAD

**Issue by piraces** [ismaro3/Cropper#5]
When "Stats" tab is clicked at the right menu it only shows "isma"... It's an error or it's unimplemented?

![captura](https://cloud.githubusercontent.com/assets/11027628/7216412/5146572c-e5ff-11e4-8175-9df2b0b80ab4.PNG)

**Comment by ismaelrh** [comment]
It has to be implemented >.<

**Comment by piraces** [comment]
Okay ;)
